name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    pull_request:
      types:
        - opened

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test Python dependenfies
        run: pip install -r molecule/default/requirements.txt

      - name: Run Molecule tests
        run: molecule test
